### ISSUE TITLE
load_las est une classmethod - risque d'erreur si accès concurrent ?

### ISSUE THREAD

**Issue by CharlesGaydon** [IGNF/myria3d#19]
Par contre le classmethod semble nécessaire pour pouvoir spécifier directement la fonction dans le paramétrage hydra qui indique la fonction de chargement. 
Ca se passe dans la  description de dataset :

```
# loading functions for data object prepared via lidar_multiclass/datamodule/data.py
load_las_func:
  _target_: functools.partial
  _args_:
    - "${get_method:lidar_multiclass.data.loading.FrenchLidarDataLogic.load_las}"
```
On pourrait envisager de remplace par une fonction directement mais ça oblige à créer une fonction avec une signature à rallonge. Effectivement le risque de concurrence d'accès existe, même si il me semble faible ; la classe n'est pas modifiée par la méthode.

_Originally posted by @CharlesGaydon in https://github.com/IGNF/lidar-deep-segmentation/pull/14#discussion_r873899531_
