### ISSUE TITLE
Dependencies broken for production release ?

### ISSUE THREAD

**Issue by phardy-egis** [IGNF/myria3d#54]
Thank you for your work and sharing it as Open-Source.

I noticed that the file `proto151_V2.0_epoch_100_Myria3DV3.1.0_predict_config_V3.1.0` has the following content for `predict` command:

```yaml
predict:
        CopyFullPos:
          _target_: myria3d.pctl.transforms.transforms.CopyFullPos
        GridSampling:
          _target_: torch_geometric.transforms.GridSampling
          _args_:
          - 0.25
        MinimumNumNodes:
          _target_: myria3d.pctl.transforms.transforms.MinimumNumNodes
          _args_:
          - 300
        MaximumNumNodes:
          _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
          _args_:
          - 40000
        CopySampledPos:
          _target_: myria3d.pctl.transforms.transforms.CopySampledPos
        Center:
          _target_: torch_geometric.transforms.Center
```

It thus makes reference to `myria3d.pctl.transforms.transforms.MinimumNumNodes` class, which is called when we run `myria3d.predict` command.

**This class is not provided inside the file the production release: [URL Prod Release](https://github.com/IGNF/myria3d/releases/tag/prod-release-tag)**

The `class MinimumNumNodes` does not appear in the file part of release source (the file referenced in by the release commit does not have this class either: [URL pointing to transform.py used in production release](https://github.com/IGNF/myria3d/blob/506f3f6238afbaef6d8e8cc821e0ebe559bcdcb1/myria3d/pctl/transforms/transforms.py) )

**Would it be possible to update the sources attached to production release to get an actually working release ?**

A first help could be to provide the commit SHA pointing to the correct dependencies to be used for production.

Thank you in advance for your help.
Feel free to email me in french.
